@CLIENT_ID=sb-c511aa1b-4d8d-4260-aa3f-e34aac3682e7!b352783|xsuaa_std!b318061
@PASSWORD=11a8b680-6dba-4836-a352-fca689671ac7$kdmKY5yqy-tNKJUv5U5hpz7Xm7fEh9q68Bil3J4Xo4I=
@AUTH_URL=https://llm-sandbox-mwyoqo2v.authentication.eu12.hana.ondemand.com
@AI_CORE_API_URL=https://api.ai.intprod-eu12.eu-central-1.aws.ml.hana.ondemand.com

# @name login
POST {{AUTH_URL}}/oauth/token?grant_type=client_credentials HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{CLIENT_ID}}:{{PASSWORD}}

@authToken = {{login.response.body.access_token}}

###

# @name getDeployments
GET {{AI_CORE_API_URL}}/v2/lm/deployments HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json
AI-Resource-Group: default

###

# @name getScenarios
GET {{AI_CORE_API_URL}}/v2/lm/scenarios HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json
AI-Resource-Group: default

###

# @name getConfigurations
GET {{AI_CORE_API_URL}}/v2/lm/configurations HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json
AI-Resource-Group: default

###

@CONF_NAME="alejandro_gemini_1.5_pro"
@EXECUTABLE_ID="gcp-vertexai"
@MODEL_NAME="gemini-1.5-pro"
@MODEL_VERSION="latest"

# @name createConfiguration
POST {{AI_CORE_API_URL}}/v2/lm/configuration HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json
AI-Resource-Group: default

{
	"name": "{{CONF_NAME}}",
	"executableId": "{{EXECUTABLE_ID}}",
	"scenarioId": "foundation-models",
	"versionId": "0.0.1",
	"parameterBindings": [
		{
			"key": "modelName",
			"value": "{{MODEL_NAME}}"
		},
		{
			"key": "modelVersion",
			"value": "{{MODEL_VERSION}}"
		}
    ],
	"inputArtifactBindings": []
}

###

curl --request POST "{{AI_CORE_API_URL}}/v2/lm/configurations" \
	--header "Authorization: Bearer {{authToken}}" \
	--header "ai-resource-group: default" \
	--header "Content-Type: application/json" \
	-d '{
	"name": "{{CONF_NAME}}",
	"executableId": "{{EXECUTABLE_ID}}",
	"scenarioId": "foundation-models",
	"versionId": "0.0.1",
	"parameterBindings": [
		{
			"key": "modelName",
			"value": "{{MODEL_NAME}}"
		},
		{
			"key": "modelVersion",
			"value": "{{MODEL_VERSION}}"
		}
    ],
	"inputArtifactBindings": []
	}'